{
  "title":"Toma-Dashboard",
  "Fliesen":[
    {
      "tile":"Etikett",
      "Reihe":1,
      "col":1,
      "row_span":1,
      "col_span":4,
      "text":"Übersicht"
    },{
      "tile":"stapel",
      "Reihe":2,
      "col":1,
      "row_span":1,
      "col_span":1,
      "title":"Gesamt",
      "wert":"6",
      "label":"Dienste"
    },{
      "tile":"stapel",
      "Reihe":2,
      "col":2,
      "row_span":1,
      "col_span":1,
      "title":"OK",
      "wert":"5",
      "label":"Dienste"
    },{
      "tile":"stapel",
      "Reihe":2,
      "col":3,
      "row_span":1,
      "col_span":1,
      "title":"FEHLER",
      "wert":"1",
      "label":"Dienste",
      "text_color":"#000000",
      "background":"#FF6666"
    },{
      "tile":"stapel",
      "Reihe":2,
      "col":4,
      "row_span":1,
      "col_span":2,
      "title":"DB-Datenträger",
      "wert":"61%",
      "label":"123 \/ 200 GB"
    },{
      "tile":"bar_graph",
      "Reihe":4,
      "col":1,
      "row_span":1,
      "col_span":4,
      "title":"Anmeldeanfragen \/ Stunde",
      "Daten":[
        {"x":"1h","y":340},
        {"x":"2h","y":450},
        {"x":"3h","y":130},
        {"x":"4h","y":240},
        {"x":"5h","y":180},
        {"x":"6h","y":40},
        {"x":"7h","y":110},
        {"x":"8h","y":120},
        {"x":"9h","y":140},
        {"x":"10h","y":70},
        {"x":"11h","y":160},
        {"x":"12h","y":360}
      ]
      },{
        "tile":"Etikett",
        "Reihe":5,
        "col":1,
        "row_span":1,
        "col_span":4,
        "text":"Status"
      },{
        "tile":"Etikett",
        "Reihe":6,
        "col":1,
        "row_span":1,
        "col_span":1,
        "text":"OK",
        "text_color":"#000000",
        "background":"#66FF66"
      },{
        "tile":"Etikett",
        "Reihe":6,
        "col":2,
        "row_span":1,
        "col_span":3,
        "text":"Autorisierungsdienst"
      },{
        "tile":"Etikett",
        "Reihe":7,
        "col":1,
        "row_span":1,
        "col_span":1,
        "text":"OK",
        "text_color":"#000000",
        "background":"#66FF66"
      },{
        "tile":"Etikett",
        "Reihe":7,
        "col":2,
        "row_span":1,
        "col_span":3,
        "text":"Daten-API"
      },{
        "tile":"Etikett",
        "Reihe":8,
        "col":1,
        "row_span":1,
        "col_span":1,
        "text":"OK",
        "text_color":"#000000",
        "background":"#66FF66"
      },{
        "tile":"Etikett",
        "Reihe":8,
        "col":2,
        "row_span":1,
        "col_span":3,
        "text":"Cache-Ebene"
      },{
        "tile":"Etikett",
        "Reihe":9,
        "col":1,
        "row_span":1,
        "col_span":1,
        "text":"OK",
        "text_color":"#000000",
        "background":"#66FF66"
      },{
        "tile":"Etikett",
        "Reihe":9,
        "col":2,
        "row_span":1,
        "col_span":3,
        "text":"Nachrichtenwarteschlange"
      },{
        "tile":"Etikett",
        "Reihe":10,
        "col":1,
        "row_span":1,
        "col_span":1,
        "text":"FEHLER",
        "text_color":"#000000",
        "background":"#FF6666"
      },{
        "tile":"Etikett",
        "Reihe":10,
        "col":2,
        "row_span":1,
        "col_span":3,
        "text":"Load-Balancer (1 Webserver down)"
      },{
        "tile":"Etikett",
        "Reihe":11,
        "col":1,
        "row_span":1,
        "col_span":1,
        "text":"OK",
        "text_color":"#000000",
        "background":"#66FF66"
      },{
        "tile":"Etikett",
        "Reihe":11,
        "col":2,
        "row_span":1,
        "col_span":3,
        "text":"Datenbank"
      }
    ]
  }
